sudo: false
language: php

matrix:
  include:
    - php: 7.1
      env: MATRIX_JOB=api
    - php: 7.1
      env: MATRIX_JOB=web

install:
  - if test "${MATRIX_JOB}" == "web"; then nvm install 8.5.0; fi
  - make "${MATRIX_JOB}-install"

before_script:
  - phpenv config-rm xdebug.ini
  - cd $TRAVIS_BUILD_DIR

script:
  - make "${MATRIX_JOB}-ci"

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.yarn-cache

notifications:
  email:
    on_success: never

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
