sudo: false

jobs:
  include:
    - stage: test
      language: php
      php: '7.1'
      before_script: phpenv config-rm xdebug.ini
      env: JOB=api
      install: make api-install
      script: make api-ci
    - language: node_js
      node_js: 8
      env: JOB=web
      install: make web-install
      script: make web-ci
    - stage: deploy
      if: branch = master
      language: node_js
      node_js: 8
      env: JOB=deploy-playground
      script: node -e "console.log('ship it to playground')"
    - if: tag =~ ^\d+\.\d+\.\d+$
      language: node_js
      node_js: 8
      env: JOB=deploy-production
      script: node -e "console.log('ship it to production')"

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.yarn-cache

notifications:
  email:
    on_success: never

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
