version: "2"
services:
    api:
        build:
            dockerfile: ./docker/Dockerfile-api
            context: .
        ports:
            - 1337:80
        environment:
          - APP_ENV=DEVELOPMENT
          - DATABASE_DSN=sqlite:////var/www/var/cyberschall.sqlite
        cpu_shares: 1024
